### ISSUE TITLE
rust/naming: short variable names

### ISSUE THREAD

**Issue by nrc** [pingcap/style-guide#5]
Should we permit short variable names for local variables with short scope?

cc @BusyJay

**Comment by BusyJay** [comment]
For example, in closure, it's more comprehensive to write short name instead of the long one.
```
vec![2, 3].into_iter().fold(0, |l, r| l + r)
```

**Comment by BusyJay** [comment]
I'm personally highly influenced by Scala style, where brevity is a convention.
